sudo: required
services:
  - docker

before_install:
  - docker build -t princeoncada/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true princeoncada/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'frontend'
  env: 'Frontend-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-891377335706'
  bucket_path: 'frontend'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY